import image from '^assets/images';

const images = [
	image.work.cos_white_bag_carried_by_woman_with_brown_coat,
	image.work.cos_charcoal_invites,
	image.work.cos_new_york_billboard_1,
	image.work.cos_light_gray_label_and_restore_label,
	image.work.cos_store_front,
	image.work.cos_to_and_from_cards_closed_and_open,
	image.work.cos_white_bag_on_pavement,
	image.work.cos_white_bags,
	image.work.cos_white_posters_in_new_york,
	image.work.cos_x_dia_pamphlet_front,
	image.work.cos_x_dia_pamphlet_open,
	image.work.tommy_hilfiger_red_blue_collage_2,
	image.work.tommy_hilfiger_red_blue_collage_1,
	image.work.tommy_hilfiger_3_red_blue_collage_posters,
	image.work.bodies_inside_out_booklets_open,
	image.work.bodies_inside_out_booklets_front,
	image.work.burberry_grey_box,
	image.work.cos_beige_invite_with_white_envelope,
	image.work.cos_charcoal_invite_with_charcoal_envelope,
	image.work.cos_black_shirt_with_white_label,
	image.work.cos_cloth_bag_serpentine_gallery,
	image.work.cos_frankfurt_installation,
	image.work.cos_gray_bag_negative_space_logo_with_blue_highlight_front,
	image.work.cos_gray_bag_negative_space_logo_with_multi_coloured_highlight_front,
	image.work.cos_gray_bag_negative_space_logo_with_white_highlight_front,
	image.work.cos_gray_bag_negative_space_logo_with_white_highlight_side,
	image.work.cos_green_black_season_greeting_cards,
	image.work.cos_green_black_season_greeting_cards_2,
	image.work.cos_green_black_season_greeting_cards_3,
	image.work.cos_grey_and_black_bags,
	image.work.cos_label_and_restore_label_black_handbag,
	image.work.cos_new_york_billboards_1,
	image.work.cos_paper_bag,
	image.work.cos_paper_bag_2,
	image.work.cos_paper_bags,
	image.work.cos_paper_bags_2,
	image.work.cos_paper_bags_black,
	image.work.cos_piete_uomo_pamphlets_open,
	image.work.cos_pittie_uomo_pamphlets_closed,
	image.work.cos_tape,
	image.work.cos_white_bag_held_by_woman,
	image.work.cos_white_bags_and_labels,
	image.work.cos_white_coat_white_label,
	image.work.cos_white_paper_packaging,
	image.work.cos_white_shirt_white_label_and_yellow_restore_label,
	image.work.modular_deco_in_bag,
	image.work.modular_deco_stacked,
	image.work.moscow_guide_1,
	image.work.moscow_guide_2,
	image.work.moscow_guide_3,
	image.work.panike_black_labels_on_pink_bg
];

export default images;
