import bodies_inside_out_booklets_front from '../_files/images/bodies_inside_out-booklets-front.jpg?w=2400&format=avif;webp;jpg&as=picture&imagetools'
import bodies_inside_out_booklets_open from '../_files/images/bodies_inside_out-booklets-open.jpg'

import burberry_grey_box from '../_files/images/burberry-grey_box.jpg'

import cos_beige_invite_with_white_envelope from '../_files/images/cos-beige_invite_with_white_envelope.jpg'
import cos_black_shirt_with_white_label from '../_files/images/cos-black_shirt_with_white_label.jpg'
import cos_cards_and_envelopes_made_of_card from '../_files/images/cos-cards_and_envelopes_made_of_card.jpg'
import cos_charcoal_invite_with_charcoal_envelope from '../_files/images/cos-charcoal_invite_with_charcoal_envelope.jpeg'
import cos_charcoal_invites from '../_files/images/cos-charcoal_invites.jpg'
import cos_cloth_bag_serpentine_gallery from '../_files/images/cos-cloth_bag-serpentine_gallery.jpg'
import cos_frankfurt_installation from '../_files/images/cos-frankfurt_installation.jpg'
import cos_gray_bag_negative_space_logo_with_blue_highlight_front from '../_files/images/cos-gray_bag-negative_space_logo_with_blue_highlight-front.png'
import cos_gray_bag_negative_space_logo_with_multi_coloured_highlight_front from '../_files/images/cos-gray_bag-negative_space_logo_with_multi_coloured_highlight-front.png'
import cos_gray_bag_negative_space_logo_with_white_highlight_front from '../_files/images/cos-gray_bag-negative_space_logo_with_white_highlight-front.jpg'
import cos_gray_bag_negative_space_logo_with_white_highlight_side from '../_files/images/cos-gray_bag-negative_space_logo_with_white_highlight-side.jpg'
import cos_green_black_season_greeting_cards from '../_files/images/cos-green_black_season_greeting_cards.jpg'
import cos_green_black_season_greeting_cards_2 from '../_files/images/cos-green_black_season_greeting_cards-2.jpg'
import cos_green_black_season_greeting_cards_3 from '../_files/images/cos-green_black_season_greeting_cards-3.jpg'
import cos_grey_and_black_bags from '../_files/images/cos-grey_and_black_bags.jpg'
import cos_label_and_restore_label_black_handbag from '../_files/images/cos-label_and_restore_label-black_handbag.jpg'
import cos_light_gray_label_and_restore_label from '../_files/images/cos-light_gray_label_and_restore_label.jpg'
import cos_new_york_billboard_1 from '../_files/images/cos-new_york_billboard-1.jpeg'
import cos_new_york_billboards_1 from '../_files/images/cos-new_york_billboards-1.jpg'
import cos_paper_bag_2 from '../_files/images/cos-paper_bag-2.jpg'
import cos_paper_bag from '../_files/images/cos-paper_bag.jpg'
import cos_paper_bags_2 from '../_files/images/cos-paper_bags-2.jpg'
import cos_paper_bags_black from '../_files/images/cos-paper_bags-black.jpg'
import cos_paper_bags from '../_files/images/cos-paper_bags.png'
import cos_piete_uomo_pamphlets_open from '../_files/images/cos-piete_uomo-pamphlets-open.jpg'
import cos_pittie_uomo_pamphlets_closed from '../_files/images/cos-pittie_uomo-pamphlets-closed.jpg'
import cos_store_front from '../_files/images/cos-store_front.jpeg'
import cos_tape from '../_files/images/cos-tape.jpg'
import cos_to_and_from_cards_closed_and_open from '../_files/images/cos-to_and_from_cards-closed_and_open.jpg'
import cos_white_bag_carried_by_woman_with_brown_coat from '../_files/images/cos-white_bag-carried_by_woman_with_brown_coat.jpg'
import cos_white_bag_held_by_woman from '../_files/images/cos-white_bag-held_by_woman.jpg'
import cos_white_bag_on_pavement from '../_files/images/cos-white_bag-on_pavement.jpg'
import cos_white_bags from '../_files/images/cos-white_bags.jpg'
import cos_white_bags_and_labels from '../_files/images/cos-white_bags_and_labels.jpg'
import cos_white_coat_white_label from '../_files/images/cos-white_coat-white_label.jpg'
import cos_white_paper_packaging from '../_files/images/cos-white_paper_packaging.jpg'
import cos_white_posters_in_new_york from '../_files/images/cos-white_posters_in_new_york.jpeg'
import cos_white_shirt_white_label_and_yellow_restore_label from '../_files/images/cos-white_shirt-white_label_and_yellow_restore_label.jpg'
import cos_x_dia_pamphlet_front from '../_files/images/cos-x_dia-pamphlet-front.jpg'
import cos_x_dia_pamphlet_open from '../_files/images/cos-x_dia-pamphlet-open.jpg'

import modular_deco_in_bag from '../_files/images/modular_deco-in_bag.jpg'
import modular_deco_stacked from '../_files/images/modular_deco-stacked.jpg'

import moscow_guide_1 from '../_files/images/moscow_guide-1.jpg'
import moscow_guide_2 from '../_files/images/moscow_guide-2.jpg'
import moscow_guide_3 from '../_files/images/moscow_guide-3.jpg'

import panike_black_labels_on_pink_bg from '../_files/images/panike-black_labels_on_pink_bg.png'

import tommy_hilfiger_red_blue_collage_1 from '../_files/images/tommy-hilfiger-red_blue_collage-1.jpg'
import tommy_hilfiger_red_blue_collage_2 from '../_files/images/tommy-hilfiger-red_blue_collage-2.jpg'

const work = {
}

export default work